apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    lighthouse.jenkins-x.io/prependStepsURL: https://raw.githubusercontent.com/jenkins-x/jx3-pipeline-catalog/60bed6408732c1eda91a15713f51a9f97dcb1757/tasks/git-clone/git-clone.yaml
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: chart
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          name: ""
          resources: {}
          workingDir: /workspace/source
        steps:
        - image: gcr.io/jenkinsxio/jx-release-version:1.0.46
          name: next-version
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx-release-version > VERSION
        - image: gcr.io/jenkinsxio/jx-boot:3.1.157
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env sh
            jx gitops variables
        - image: golang:1.15
          name: release-binary
          resources: {}
          script: |
            #!/usr/bin/env bash
            source .jx/variables.sh
            make release
        - image: gcr.io/jenkinsxio/jx-changelog:0.0.25
          name: changelog
          script: |
            #!/usr/bin/env sh
            source .jx/variables.sh

            git commit -a -m "chore: release $VERSION" --allow-empty
            git tag -fa v$VERSION -m "Release version $VERSION"
            git push origin v$VERSION

            jx changelog create --verbose --header-file=hack/changelog-header.md --version=$VERSION --rev=$PULL_BASE_SHA --output-markdown=changelog.md --update-release=false
        - command:
          - jx-updatebot
          - pr
          image: gcr.io/jenkinsxio/jx-updatebot:0.0.45
          name: promote-release
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
